// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3b1Lth3H5xe7s4FDjT-aJhuP81i-90Ro',
    appId: '1:854797188530:android:770622ad90a3ef297038ab',
    messagingSenderId: '854797188530',
    projectId: 'bored-35372',
    storageBucket: 'bored-35372.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdLBQWtREp7g9o0PgP3HP5cI938CU9kAM',
    appId: '1:854797188530:ios:5cdb40b6a19971f07038ab',
    messagingSenderId: '854797188530',
    projectId: 'bored-35372',
    storageBucket: 'bored-35372.appspot.com',
    iosClientId: '854797188530-dv01lu2tcbcd6eoav0kifr51o6k6ssic.apps.googleusercontent.com',
    iosBundleId: 'com.example.bored',
  );
}
